# --- TGW parameters ---
TGW_weather_years: ['2058'] # Options: 2018 | 2058
TGW_scenario: 'rcp85hotter' # Options: historical (for TGW_weather_year < 2020) | rcp45cooler | rcp45hotter | rcp85cooler  | rcp85hotter

# --- SMART-DS parameters ---
# Regions
# CITY_REGIONS_TO_RUN:
#     GSO: ["rural", "industrial", "urban-suburban"]
#     AUS: ["P1R", "P1U", "P2U"]
#     SFO: ["P1R", "P1U", "P2U"]
# CITY_REGIONS_TO_RUN:
#     GSO: ["urban-suburban"]
#     AUS: ["P1R", "P1U", "P2U"]
#     SFO: ["P1R", "P1U", "P2U"]
CITY_REGIONS_TO_RUN:
    GSO: ["rural"]
# Years
smart_ds_years:
  - "2018"
# building types (res - residential, com - commercial)
building_types: ["res", "com"]

# --- Regression model paramaters ---
# Aggregation level of demand
aggregation_level: "feeder"  # options: building | feeder | regional
# Input features set
X_columns_set: "X_columns_D" # options: X_columns_A (time+weather) | X_columns_B (only high corr weather) | X_columns_C (only temp) | X_columns_D (additional features)
# model output
Y_column: "heating_kw"  # options:  cooling_kw_sum | heating_kw | total_site_electricity_kw
# demand prediction mode
demand_mode: 'MLP'
# Regression model
prediction_model_cooling: "MLP_2_512_64" # options: | MLP_1_1452_1 (Mai) | MLP_2_4096_512 | MLP_2_2048_256 | MLP_2_1024_128 | MLP_1_1024 | MLP_2_512_64 | MLP_2_256_32 | MLP_2_100_10 | MLP_2_32_16 | MLP_1_16 | PWLR_4bp | Poly_4deg | LR
prediction_model_heating: "MLP_2_1024_128" 

# Months for training (inclusive)
start_month: 1
end_month: 12

# --- Path input/output parameters ---
# name of inputs dictionary for training
input_data_dict_name: "input_data_dict_proc" # options: input_data_dict_proc -  Input data with additional features and without redundant features | 'input_data_dict' - Raw data with minimal processing
# Define default paths for saving/loading input and output data (path is updated by src/inputs_ops/load_config() for the months and aggregation level defined in this file)
# path to input data for training (ResStock weather and load)
input_data_training_path: "/nfs/turbo/seas-mtcraig-climate/Aviad/load_prediction/results/data/training/2018/months_6_8/ml_input_data/resstock/amy2018/regional/" # old name - input_data_dict_path
# path to output data (model, scalers, performance metrics)
output_data_training_path: "/nfs/turbo/seas-mtcraig-climate/Aviad/load_prediction/results/data/training/2018/months_6_8/ml_output_data/total_site_electricity_kw/regional/" # old name - output_data_path
# path to input data for prediction (TGW weather)
input_data_prediction_path: "/nfs/turbo/seas-mtcraig-climate/Aviad/load_prediction/results/data/prediction/input/TGW_weather/Concord/Historical/" 
# path to output data from prediction (demand profiles)
output_data_prediction_path: "/nfs/turbo/seas-mtcraig-climate/Aviad/load_prediction/results/data/prediction/output/2018/months_1_12/heating_kw/feature_A/regional/all_regions" 
# path to smart-ds load data
smart_ds_load_path: "/nfs/turbo/seas-mtcraig-climate/Aviad/load_prediction/results/data/smart_ds_load"

# --- Model training/prediction sets of input features and output labels ---
# Output labels - all columns from the smart-ds parquet files
Y_columns:
  - "total_site_electricity_kw"
  - "total_site_electricity_kvar"
  - "heating_kw"
  - "heating_kvar"
  - "cooling_kw"
  - "cooling_kvar"
  - "lighting_kw"
  - "lighting_kvar"
  - "fans_kw"
  - "fans_kvar"
  - "pumps_kw"
  - "pumps_kvar"
  - "water_systems_kw"
  - "water_systems_kvar"
  - "refrigeration_kw"
  - "refrigeration_kvar"
  - "motors_kw"
  - "motors_kvar"
  - "plug_loads_kw"
  - "plug_loads_kvar"
  - "clothes_dryer_kw"
  - "clothes_dryer_kvar"
  - "clothes_washer_kw"
  - "clothes_washer_kvar"
  - "stove_kw"
  - "stove_kvar"
  - "dishwasher_kw"
  - "dishwasher_kvar"

### Input Features sets ###

# Input Features - updated by src/input_ops/load_config() using 'X_columns_set' defined in this file (e.g., to X_columns_A/B/C/D)
X_columns:
  - "year"
  - "month"
  - "day"
  - "hour"
  - "weekday"
  - "weekend"
  - "Dry Bulb Temperature [°C]"
  - "Relative Humidity [%]"
  - "Wind Speed [m/s]"
  - "Wind Direction [Deg]"
  - "Global Horizontal Radiation [W/m2]"
  - "Direct Normal Radiation [W/m2]"
  - "Diffuse Horizontal Radiation [W/m2]"
  
# all weather variable + some simple time variables that were derived from date_time
X_columns_A:
  - "year"
  - "month"
  - "day"
  - "hour"
  - "weekday"
  - "weekend"
  - "Dry Bulb Temperature [°C]"
  - "Relative Humidity [%]"
  - "Wind Speed [m/s]"
  - "Wind Direction [Deg]"
  - "Global Horizontal Radiation [W/m2]"
  - "Direct Normal Radiation [W/m2]"
  - "Diffuse Horizontal Radiation [W/m2]"

# Input Features that have a high correlation with cooling and heating (some radiation were droped due to multicolinearity [high correlation between them so some were redundant]) 
X_columns_B:
  - "Dry Bulb Temperature [°C]"
  - "Global Horizontal Radiation [W/m2]"
  - "Relative Humidity [%]"
  - "Wind Speed [m/s]"

# Input Features for testing
X_columns_C:
  - "Dry Bulb Temperature [°C]"

# Input Features for testing
X_columns_D:
  - "year"
  - "month"
  - "day"
  - "hour"
  - "weekday"
  - "weekend"
  - "Dry Bulb Temperature [°C]"
  - "Relative Humidity [%]"
  - "Wind Speed [m/s]"
  - "Wind Direction [Deg]"
  - "Global Horizontal Radiation [W/m2]"
  # - "Direct Normal Radiation [W/m2]"
  # - "Diffuse Horizontal Radiation [W/m2]"
  - "last 24h avg Temp"
  - "last 12h avg Temp"
  - "Minus 1h Temp"
  - "Minus 3h Temp"
  - "Minus 6h Temp"
  - "Minus 12h Temp"
  - "Minus 24h Temp"
  - "sin hour"
  - "cos hour"
  - "temp times sin hour"
  - "temp times cos hour"


